version: "3.9"

services:
  database:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rasterizer
    volumes:
      - rasterizer_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webdriver:
    build:
      context: ./docker
      dockerfile: Dockerfile.webdriver
    ports:
      - 4444:4444

volumes:
  rasterizer_data:
